# -*- coding: UTF-8 -*-
# Generated by Selenium IDE
import pytest
from selenium import webdriver
from selenium.webdriver.common.by import By


class TestDemo1():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.driver.implicitly_wait(3000)

    def teardown_method(self, method):
        self.driver.quit()

    def test_demo1(self):
        self.driver.get("https://ceshiren.com/")
        self.driver.set_window_size(1440, 900)
        self.driver.find_element(By.LINK_TEXT, "所有分类").click()
        #断言

        myclass = self.driver.find_element(By.LINK_TEXT,"所有分类").get_attribute("class")
        # print(myclass)
        assert  "active" == myclass